- name: loops playbook
  hosts: local
  become: yes
  connection: local
  tasks:
    - name: basic loops
      loop:
        - python
        - shell
        - ansible
      ansible.builtin.debug:
        msg: "{{ item }}"
    - name: advance loops
      loop:
        - { name: "mutali", age: 200 }
        - { name: "lueyeu", age: 2023 }
      ansible.builtin.debug:
        msg: "{{ item.name }}"
    - name: install
      loop:
        - mysql-server
        - nginx
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
    - name: start the service
      loop:
        - mysqld
        - nginx
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
    - name: facts
      ansible.builtin.debug:
        msg: " {{ ansible_facts }}"
