- name: loops playbook
  hosts: local
  connection: local
  tasks:
    - name: basic loops
      loop:
        - python
        - shell
        - ansible
      ansible.builtin.debug:
        msg: "{{ item }}"
    - name: advance loops
      loop:
        - { name: "mutali", age: 200 }
        - { name: "lueyeu", age: 2023 }
      ansible.builtin.debug:
        msg: "{{ item.name }}"
    - name: install
      ansible.builtin.debug:
        msg: "readuy"
