- name: playbook1
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
    - name: install mysql-server
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: start mysql-server
      ansible.builtin.service:
        name: mysqld
        state: started
    - name: enable mysql-server
      ansible.builtin.service:
        name: mysqld
        enabled: yes
    - name: check password setup
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: 172.31.89.147
      register: mysql_info
      ignore_errors: true
    - name: root password set
      ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_root_passwor }}
      when: mysql_info.failed is true
