- name: mysql server setup
  hosts: mysql
  connection: local
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
  tasks:
    - name: Install MySQL libraries
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - cryptography
        - PyMySQL
    - name: install mysql-server
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: start mysql-server
      ansible.builtin.service:
        name: mysqld
        state: started
    - name: enable mysql-server
      ansible.builtin.service:
        name: mysqld
        enabled: yes
    - name: root password setup check
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: 172.31.91.66
      register: mysql_info
      ignore_errors: true
    - name: roots password set
      ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_root_password }}
      when: mysql_info.failed is true
    - name: print mysql_info
      ansible.builtin.debug:
        msg: "{{ mysql_info }}"
