- name: playbook 1
  hosts: local
  connection: local
  tasks:
    - name: set fact
      ansible.builtin.set_fact:
        user_name: "maiu"
        prof: "software"
    - name: access set-vars
      ansible.builtin.debug:
        msg: "{{ user_name }} and {{ prof }}"
