- name: ping the server 
  hosts: local
  connection: local
  tasks:
    - name: ping the server
      ansible.builtin.ping:
    - name: hello the server 
      ansible.builtin.debug:
        msg: "helo to server"