- name: conditions
  hosts: local
  connection: local
  tasks:
    - name: conditions
      vars:
        age: 40
      ansible.builtin.debug:
        msg: "{{ age }} and murali"
      when: age>20
    - name:
      ansible.builtin.package:
        name: git
        state: present
      when: ansible.os_family == "RedHat"
