- name: variables
  hosts: local
  connection: local
  vars:
    user: "murali"
    age: 20
  vars_files:
    - var_files.yaml
  vars_prompt:
    name: city
    prompt: "enter city"
  tasks:
    - name: vars locally
      vars:
        user: kinod
      ansible.builtin.debug:
        msg: "{{ user }} and {{ age }} and {{ Country }} and {{ body }} and {{ city }} {{ bp }}"