- name: shell module and command module
  hosts: local
  connection: local
  tasks:
    - name: shell module
      ansible.builtin.shell: ls -l
      register: command_output
    - name: print the complete output
      ansible.builtin.debug:
        msg: "{{ command_output }}"
    - name: print stdout
      ansible.builtin.debug:
        msg: "{{ command_output.stdout }}"
    - name: print command exit status - success or failure
      ansible.builtin.debug:
        msg: "{{ command_output.rc }}"
