- name: set facts playbook
  connection: local
  hosts: local
  tasks:
    - name: task1
      ansible.builtin.set_fact:
        my_name: "murali 211"
        city: "bng"
    - name: task2
      ansible.builtin.debug:
        msg: "{{ my_name }}"
    - name: task3
      ansible.builtin.debug:
        msg: "{{ city }}"
