- name: variables in ansible
  hosts: local
  connection: local
  vars:
    user: murali
    age: 20
  tasks:
    - name: locally
      vars:
        user: kinod
      ansible.builtin.debug:
        msg: "{{ user }} and {{ age }}"