- name: ping the server
  hosts: local
  connection: local
  tasks:
    - name: ping new server
      ansible.builtin.ping:
    - name: hello the server
      ansible.builtin.debug:
        msg: "hello server"
