- name: variables
  hosts: local
  connection: local
  vars:
    user: "murali"
    age: 20
  vars_files:
    - var_files.yaml
  tasks:
    - name: vars locally
      vars:
        user: kinod
      ansible.builtin.debug:
        msg: "{{ user }} and {{ age }} and {{ country }}"