- name: varibale types
  hosts: local
  connection: local
  vars:
    Name: Mutrali
    prof: enginerr
  tasks:
    - name: print locally
      vars:
        Name: Muralie
        prof: minister
      ansible.builtin.debug:
        msg: "{{ Name }} and {{ prof }}"
    - name: print from
      vars_files:
        - var_files.yaml
      ansible.builtin.debug:
        msg: "{{ country }}"