- name: functions
  hosts: local
  connection: local
  tasks:
    - name: upper to lower
      vars:
        user: "murali"
      ansible.builtin.debug:
        msg: "{{ user | upper }}"
    - name: max and min
      vars:
        numbers: [20, 2002, 233, 233]
      ansible.builtin.debug:
        msg: "{{ numbers | max }} and {{ numbers | min }}"
    - name: defualy value
      ansible.builtin.debug:
        msg: "{{ city | default('bng') }}"
    - name: string to list
      vars:
        s: "s,2,32"
      ansible.builtin.debug:
        msg: "{{ s | list }}"
