- name: conditions in ansi
  hosts: local
  connection: local
  vars:
    age: 2020
    user_id: 21
    note: "hgwooo world@@"
  tasks:
    - name: cond in ansi
      ansible.builtin.debug:
        msg: "{{ note }}"
      when: age == 2020
    - name: basic loops
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - git
        - nginx
        - mysql-server
    - name: advance loops
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: nginx, state: absent }
        - { name: gcc, state: present }
