- name: playbook2
  connection: local
  hosts: local
  become: yes
  gather_facts: no
  tasks:
    - name: shell module
      ansible.builtin.shell: touch /tmp/f1.txt
      register: command_result
    - name: print comand ouput
      ansible.builtin.debug:
        msg: "{{ command_result }}"
