- name: variables
  hosts: local
  connection: local
  vars:
    name: murali
    age: 33
  vars_files:
    - vars_files.yaml
  vars_prompt:
    - name: gender
      prompt: "enter gender"
  tasks: 
    - name: task level vars
      vars:
        age: 20
      ansible.builtin.debug:
        msg: "{{ name }} and {{ age }} and {{ country }} {{ gender }} {{ job }} and {{ city }}"
  