- name: playbook 1
  hosts: local
  connection: local
  vars:
    user_name: "murali"
  vars_files:
    - file.yaml
  vars_prompt:
    - name: salary
      prompt: "enter the salary "
  tasks:
    - name: msg the server
      vars:
        name: "bindo"
      ansible.builtin.debug:
        msg: "{{ user_name }} {{ state }} {{ country }} {{ salary }} {{ age }}"
