- name: playbook 1
  hosts: local
  connection: local
  tasks:
    - name: ping the server
      ansible.builtin.ping:
    - name: msg the ansible-server
      ansible.builtin.debug:
        msg: "Hai server"
