- name: playbook to create ec2 instances
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0c79c481ed81c4305
    security_group: sg-09002db929ad2ff12
    image_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
  tasks:
    - name: create ec2-instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
      loop:
        - mysql
        - backend
        - frontend
      register: ec2_info
