- name: playb1
  hosts: local
  connection: local
  tasks:
    - name: condi in ansi
      vars:
        user: "kumar222"
        id: 220
      ansible.builtin.debug:
        msg: "{{ user }}"
      when: id >= 200
    - name: register ansible_facts
      ansible.builtin.debug:
        msg: "no action task"
      register: ansible_facts
    - name: doing Os specific
      ansible.builtin.debug:
        msg: "hello Redhat"
      when: ansible_facts.os_family == "RedHat"
    - name: doing Os specific2
      ansible.builtin.debug:
        msg: "debian"
      when: ansible_facts.os_family == "debian"
