- name: multiple plays in playbook
  hosts: local
  connection: local
  tasks:
    - name: hello message
      ansible.builtin.debug:
        msg: "helkolll"
- name: second playbook
  hosts: local
  connection: local
  tasks:
    - name: ping the server
      ansible.builtin.ping:
      