- name: create aws instances
  connection: local
  hosts: local
  vars:
    instances_names:
      - mysql
      - backend
      - frontend
    subnet_id: subnet-0f4dd395530fb0d4d
    image_id: ami-09c813fb71547fc4f
    security_group: sg-09002db929ad2ff12
    instance_type: t3.micro
    zone: emurali.shop
    type: A
    ttl: 1
  tasks:
    - name: install boto3 and botocore python libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - boto3
        - botocore
    - name: create ec2-instaces
      amazon.aws.ec2_instance:
        name: " {{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances_names }}"
      register: ec2_info.results
    - name: update route53 record for backend and database
      amazon.aws.route53:
        state: present
        zone: " {{ zone }}"
        type: " {{ type }}"
        ttl: "{{ ttl }}"
        record: "{{ item.item }}.{{ zone }}"
        value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
      loop: "{{ ec2_info.results }}"
    - name: update route53 record for frontend
      amazon.aws.route53:
        state: present
        zone: " {{ zone }}"
        type: " {{ type }}"
        ttl: "{{ ttl }}"
        record: "{{ zone }}"
        value: "{{ item.instances[0].public_ip_address }}"
        overwrite: true
      when: item.item == "frontend"
      loop: "{{ ec2_info.results }}"
