- name: variable types
  hosts: local
  connection: local
  vars:
    Name: Mutrali
    prof: engineer
  tasks:
    - name: print locally
      vars:
        Name: Muralie
        prof: minister
      ansible.builtin.debug:
        msg: "{{ Name }} and {{ prof }}"

    - name: print from var file
      vars_files:
        - var_files.yaml
      ansible.builtin.debug:
        msg: "{{ country }}"
