- name: basics playbook - play1
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: ping the server
      ansible.builtin.ping:
    - name: hello the server
      ansible.builtin.debug:
        msg: "hello server"
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
- name: play 2
  hosts: local
  connection: local
  tasks:
    - name: ping the sever again
      ansible.builtin.ping:
