- name: shell module and command module
  hosts: local
  connection: local
  tasks:
    - name: shell module
      ansible.builtin.shell: ls -l
      register: output
    - name: print the output
      ansible.builtin.debug:
        msg: "{{ output }}"
