- name: play one
  hosts: local
  connection: local
  tasks:
    - name: ping the server
      ansible.builtin.ping:
- name: play two
  hosts: local
  connection: local
  tasks:
    - name: msg the node
      ansible.builtin.debug:
        msg: "hello the server "
