- name: conditions
  hosts: local
  connection: local
  tasks:
    - name: conditions
      vars:
        age: 40
      ansible.builtin.debug:
        msg: "{{ age }} and murali"
      when: age>20
    - name: facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
      register: ansible_facts
    - name:
      ansible.builtin.package:
        name: git
        state: present
      when: os_family == "RedHat"
