- name: variables in ansible
  hosts: local
  vars:
    name: murali
    age: 20
  tasks:
    - name: vars locally
      vars:
        name: kinod
        anisble.builtin.debug:
          msg: "{{ name }} and {{ age }}"