- name: create 3 ec2-instances
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0c79c481ed81c4305
    sg_id: sg-09002db929ad2ff12
    ami_id: 09c813fb71547fc4f
    instance_type: t3.micro
    instances:
      - mysql
      - backend
      - frontend
  tasks:
    - name: create ec2-instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"
      register: ec2_info
