- name: vars in ansi
  hosts: local
  connection: local
  vars:
    user: "murali"
    age: 20
    isMarried: yes
  vars_files:
    - var_files.yaml
  vars_prompt:
    name: "city"
    prompt: "enter city"
  tasks:
    - name: task level varibales
      var:
        user: "vinod"
      ansible.builtin.debug:
        msg: "{{ user }} and {{ age }} and {{ prof }} and {{ country }} and {{ city }} and  {{ gender }}"
