- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0f4dd395530fb0d4d
    sg_id: sg-09002db929ad2ff12
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    zone: emurali.shop
    instances:
      - mysql
      - backend
      - frontend
  tasks:
    - name: Install AWS Python libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"
      register: ec2_info
