- name: ansible tags
  connection: local
  hosts: local
  tasks:
    - name: msg the server
      ansible.builtin.debug:
        msg: "hello to server"
      tags:
        - run
        - run_now
    - name: ping the server
      ansible.builtin.ping:
      tags:
        - run
