- name: playbook1
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: set the facts var
      ansible.builtin.set_fact:
        user: "ec2-user"
    - name: accessing set_fact var
      ansible.builtin.debug:
        msg: "{{ user }}"
    - name: basic loops
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - gcc
        - c
        - c++
    - name: advance loops
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: ngix, state: absent }
        - { name: zip, state: present }
