- name: conditions in ansi
  hosts: local
  connection: local
  vars:
    age: 2020
    user_id: 21
    note: "hgwooo world@@"
  tasks:
    - name: cond in ansi
      ansible.builtin.debug:
        msg: "{{ note }}"
      when: age >= 20
