- name: tags and regst
  connection: local
  hosts: local
  tasks:
    - name: lower to upper
      vars:
        user: murali
      ansible.builtin.debug:
        msg: "{{ user | upper }}"
      tags:
        - lower
        - run
    - name: shell module
      ansible.builtin.shell: echo "heloow orkd" >> /home/ec2-user/tmp.txt
      register: output
      ansible.builtin.debug:
        msg: "{{ output }}"
      tags:
        - run
    - name: command module
      ansible.builtin.command: touch f1.txt
      tags:
        - run
    - name: command module 2
      ansible.builtin.command: echo "heloow orkd" >> /home/ec2-user/tmp.txt
      tags:
        - run
