- name: create 3 ec2-instances
  hosts: local
  connection: local
  become: yes
  vars:
    subnet_id: subnet-0c79c481ed81c4305
    sg_id: sg-09002db929ad2ff12
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
      - mysql
      - backend
      - frontend
  tasks:
    - name: install boto3 and botocore
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore
    - name: create ec2-instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        instance_type: "{{ instance_type }}"
        region: us-east-1
      loop: "{{ instances }}"
      register: ec2_info
