- name: conditions
  hosts: local
  connection: local
  tasks:
    - name: conditions
      vars:
        age: 40
      ansible.builtin.debug:
        msg: "{{ age }} and murali"
      when: age>20
    - name: facts
      register: ansible_facts
      ansible.builtin.debug:
        msg: ansible_facts
    - name: install git
      ansible.builtin.package:
        name: git
        state: present
      when: ansible_facts.os_family=="RedHat"
