- name: playbook 1
  hosts: local
  connection: local
  vars:
    name: "murali"
  vars_file:
    - file.yaml
  vars_prompt:
    name: salary
    prompt: "enter the salary "
  tasks:
    - name: msg the server
      vars:
        name: "bindo"
      ansible.builtin.debug:
        msg: "{{ name }} {{ state }} {{ country }} {{ salary }} {{ age }}"
