- name: create aws instances
  connection: local
  hosts: local
  tasks:
    - name: install boto3 and botocore python libraries
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore
    - name: create ec2-instaces
      vars:
        instances_names:
          - mysql
          - backend
          - frontend
        subnet_id: subnet-0f4dd395530fb0d4d
        image_id: ami-09c813fb71547fc4f
        security_group: sg-09002db929ad2ff12
        instance_type: t3.micro
      amazon.aws.ec2_instance:
        name: " {{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        region: us-east-1
      loop: "{{ instances_names }}"
