- name: playbook1
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: print facts gathered by ansible
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
    - name: conditions in ansible
      vars:
        age: 20
      ansible.builtin.debug:
        msg: "younger"
      when: age <=20
    - name: install softwares
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - gcc
        - git
        - zip
      when: ansible_facts.os_family == "RedHat"
    - name: install packages
      ansible.builtin.package:
        name: "{{ item }}"
      loop:
        - { name: nginx, state: started }
      when: ansible_facts.os_family == "Ubuntu"
