- name: vars in ansi
  connection: local
  hosts: local
  vars:
    user: "murali21"
  vars_files:
    - vars_file.yaml
    - vars_file2.yaml
  vars_prompt:
    - name: city
      prompt: "enter city:"
  tasks:
    - name: vars task level
      vars:
        user: murali2000"
      ansible.builtin.debug:
        msg: "{{ user }} and {{ city }} and {{ country }} and {{ job }} and {{ gender }} and {{ new_file }}"
