- name: functions
  hosts: local
  connection: local
  vars:
    user: "murali"
    city: "BNG"
    numbers: [202, 30203, 20302, 03002]
    stack:
      - { "name": "murali", "age": "200" }
    desc:
      program: python
      databse: mysql
  tasks:
    - name: lower to upper
      ansible.builtin.debug:
        msg: "{{ user | upper }}"
    - name: upper to lower
      ansible.builtin.debug:
        msg: "{{ city | lower }}"
    - name: max and min
      ansible.builtin.debug:
        msg: "{{ numbers | min }} and {{ numbers | max }}"
    - name: list to map
      ansible.builtin.debug:
        msg: "{{ stack | items2dict }}"
