- name: disable nodejs
  ansible.builtin.command: dnf module disable nodejs -y
- name: enable nodejs
  ansible.builtin.command: dnf module enable nodejs:20 -y
- name: install nodejs and mysql cli
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - nodejs
    - mysql
- name: include common role
  include_role:
    name: common
- name: install dependencies
  community.general.npm:
    path: /app
- name: create ansible user
  ansible.builtin.user:
    name: ansible
- name: copy backend service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service
- name: import sql schema
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: "{{ mysql_login_user }}"
    login_password: "{{ mysql_login_password }}"
    login_host: "{{ mysql_login_host }}"
    target: /app/schema/backend.sql
- name: daemon reload and restart
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: true
    daemon_reload: true
