- name: install dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - cryptography
    - PyMySQL
- name: create mysql-server
  ansible.builtin.package:
    name: mysql-server
    state: present
- name: start and enable
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
- name: check root password is set
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: 172.31.17.117
  ignore_errors: true
  register: mysql_info
- name: set root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ mysql_root_password }}
  when: mysql_info.failed is true
