- name: delete directory
  ansible.built.file:
    path: "{{ app_location }}"
    state: absent
- name: create new directory
  ansible.built.file:
    path: "{{ app_location }}"
    state: directory
- name: download the code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component_name }}-v2.zip
    dest: "{{ app_location }}"
  remote_src: yes
